name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  YOUTUBE_MUSIC_URL: https://music.youtube.com/search
  YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
  DEEZER_API_URL: https://api.deezer.com/search
  APPLE_MUSIC_API_URL: https://music.apple.com/ca
  SOUNDCLOUD_BASE_URL: https://soundcloud.com
  TIDAL_BASE_URL: https://listen.tidal.com
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test
