name: run tests

on:
  pull_request:
    branches: [master]

env:
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
  YOUTUBE_API_SEARCH_URL: https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=1&q=
  DEEZER_API_URL: https://api.deezer.com/search
  YOUTUBE_BASE_URL: https://www.youtube.com/
  APPLE_MUSIC_BASE_URL: https://music.apple.com/us/search?term=
  TIDAL_BASE_URL: https://listen.tidal.com/search?q=
  SOUNDCLOUD_BASE_URL: https://soundcloud.com/search/sounds?q=
  REDIS_URL: redis://127.0.0.1:6379
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run integration tests
        run: bun run test
